version: "3.7"

services:
  postgres:
    image: postgres:11
    restart: always
    enviroment:
      POSTGRES_PASSWORD: example

  app:
    build:
      context: .
      dockerfile: DockerfileApp
    ports:
      - "8080"
      - "50051:50051"
      - "1234:1234"
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app

