# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cam_pb2 as cam__pb2


class SHRouteStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendDeg = channel.unary_unary(
        '/gateway.SHRoute/SendDeg',
        request_serializer=cam__pb2.HumanCount.SerializeToString,
        response_deserializer=cam__pb2.Null.FromString,
        )
    self.ChangeCC = channel.unary_unary(
        '/gateway.SHRoute/ChangeCC',
        request_serializer=cam__pb2.CC.SerializeToString,
        response_deserializer=cam__pb2.Null.FromString,
        )


class SHRouteServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendDeg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeCC(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SHRouteServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendDeg': grpc.unary_unary_rpc_method_handler(
          servicer.SendDeg,
          request_deserializer=cam__pb2.HumanCount.FromString,
          response_serializer=cam__pb2.Null.SerializeToString,
      ),
      'ChangeCC': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeCC,
          request_deserializer=cam__pb2.CC.FromString,
          response_serializer=cam__pb2.Null.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gateway.SHRoute', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
